language: node_js
node_js:
  - "7"
  - "6"
before_script: ./node_modules/nearley/bin/nearleyc.js src/grammar/grammar.ne -o src/grammar/grammar.js
script: npm test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/483a4e7f4263a7c9b023
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
